### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by hendersj** [aspiers/opensuse-spotify-installer#39]
Not so much an issue, but I wanted to thank you for the updates to this script - I pulled the zip this morning with the update to support 1.0.19, and installed it on Leap 42.1 with no problems at all.

(Feel free to close this as there is no issue to resolve - I just couldn't see a place to provide feedback)

**Comment by aspiers** [comment]
Good to know, thanks :) Hopefully we can make some more progress on this project soon, since it is beginning to gather dust ...

**Comment by hendersj** [comment]
You bet - the updates that are in
https://github.com/cornguo/opensuse-spotify-installer work with the latest
builds - I actually thought that's where I was submitting this comment to,
but all the work you've done in the past on this is greatly appreciated as
well. :)
